<?php

$labels = array();
$labels['forwarding'] = 'Weiterleitungen';
$labels['invalidaddress'] = 'Ungültige E-Mail-Adresse';
$labels['keepcopies'] = 'Kopien der original E-Mails behalten';
$labels['forwardingaddress'] = 'Weiterleiten an';
$labels['forwardingenabled'] = 'Weiterleitung aktivieren';

$messages = array();
$messages['forwardingloop'] = 'Diese Weiterleitung ist zyklisch.';
$messages['demoaccount'] = 'Dies ist ein Demo-Zugang. Weiterleitungen sind nicht erlaubt.';

?>
