<?php

$labels = array();
$labels['forwarding'] = 'Forwarding';
$labels['invalidaddress'] = 'Invalid Email Address';
$labels['keepcopies'] = 'Keep Copies of Original Messages';
$labels['forwardingaddress'] = 'Forwarding address';
$labels['forwardingenabled'] = 'Forwarding enabled';

$messages = array();
$messages['forwardingloop'] = 'This forwarding will loop';
$messages['demoaccount'] = 'This is a Demo Account. Forwarding is disallowed.';
?>
