<?php

$labels = array();
$labels['forwarding'] = 'Transfert';
$labels['invalidaddress'] = 'Adresse email invalide';
$labels['keepcopies'] = 'Garder une copie des messages originaux';
$labels['forwardingaddress'] = 'Adresse de transfert';
$labels['forwardingenabled'] = 'Transfert activé';

$messages = array();
$messages['forwardingloop'] = 'Ce transfert va boucler';
$messages['demoaccount'] = 'Ceci est un compte de démo. Le transfert n\' nest pas autorisé.';
?>
