<?php
 
$labels = array();
$labels['forwarding'] = 'Reencaminhar';
$labels['invalidaddress'] = 'Endereço de Email inválido';
$labels['keepcopies'] = 'Manter cópia das mensagens originais';
$labels['forwardingaddress'] = 'Endereço para reencaminhamento';
$labels['forwardingenabled'] = 'Reencaminhamento ativo';
 
$messages = array();
$messages['forwardingloop'] = 'Este reencaminhamento cria um ciclo infinito';
$messages['demoaccount'] = 'Esta conta é apenas de demonstração. O reencaminhamento não é permitido.';
?>
